# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Allan Khariton
description: "I'm a Data Analyst II, and advancing in my career as a data professional.  My construction portfolio highlights projects I worked on as a Construction Manager from 2018-2022, with an emphasis on technical and professional skills and growth. You can view the summaries of my past and current projects in the posts on this page, visit my Github & LinkedIn pages (or download my Resume) by using the links below, and view my data-related projects at akstl1.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Construction Management <span style="color:#f58506"> Portfolio </span>
location: "Boston, USA"
resume_url: /docs/A_Khariton_Resume_2022.08.22.pdf
avatar_image: /img/Head Shot.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/allan-khariton/" # Add your linkedln handle
github: "https://github.com/akstl1"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

